import numpy

In [5]:
import numpy as np


In [6]:
list =[1,2,3]
array = np.asarray(list)
print(array)
print(type(array))
#create list


[1 2 3]
<class 'numpy.ndarray'>


In [10]:
zero=np.zeros((3,3))
print(zero)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [11]:
eye=np.eye(5,5)
print(eye)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [12]:
print (eye*5)


[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


In [14]:
one=np.ones((3,3),dtype='int64')
print(one)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
b=one.copy()
print(b)#copying array 

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [18]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a.shape)
b=np.reshape(a,(2,5))
print(b.shape)
print(b)

(10,)
(2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [23]:
a=np.random.random((3,3))
print(a)
#o,1 default range for random

[[0.8606209  0.36028486 0.74803229]
 [0.97615833 0.15737307 0.2377393 ]
 [0.58990414 0.39647292 0.02082035]]


In [27]:
a=np.random.randint(low=-5,high=5,size=(5,5))
print(a)


[[-2 -1  0 -1 -5]
 [ 2  0 -2  1  0]
 [-4 -4 -3  2  0]
 [ 4 -1  0 -1  2]
 [-5 -2  0  0 -5]]


In [29]:
a=np.full((2,2),1.25)
print(a)

[[1.25 1.25]
 [1.25 1.25]]


In [31]:
a=np.arange(-10,10,2)
print(a)

[-10  -8  -6  -4  -2   0   2   4   6   8]


In [32]:
a=np.linspace(-1,1,5)
print(a)
#matplot_use

[-1.  -0.5  0.   0.5  1. ]


In [37]:
a=np.array([1,2,3,4,5,6])
print (a[0])
#-1 means last value
print (a[-1])
#from start to end -1
print (a[0:2])

#shipping
print[0:5:2]


1
6
[1 2]


TypeError: 'builtin_function_or_method' object is not subscriptable

In [38]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[-1: :-1])
#reversing an array

[9 8 7 6 5 4 3 2 1]


In [39]:
a=np.array([[1,2,3],[4,5,6]])# 2D array
print(a)
b=np.array(([1,2,3],[4,5,6]))
print(b)
#add
print(np.add(a,b))
#multiply
print(np.multiply(a,b))
#subtract
print(np.subtract(a,b))
#divide (float recommended)
print(np.divide(a,b))
#squareroot
print(np.sqrt(a))
            

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]
[[ 1  4  9]
 [16 25 36]]
[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [43]:
a=np.array([[1,2],[4,5]])
b=np.array([[1,2],[4,5]])
print(np.dot(a,b))

[[ 9 12]
 [24 33]]


In [44]:
#sum
print(a)
#sum along each column
print(np.sum(a,axis=0))# vertical column
print('-'*20)
#sum along each row
print(np.sum(a,axis=1))#horizontal row
#average
print(np.average(a))
#transpose
print(np.transpose(a))



[[1 2]
 [4 5]]
[5 7]
--------------------
[3 9]
3.0
[[1 4]
 [2 5]]


In [4]:
import pandas as  pd



In [49]:
pd.read_csv  #comma separated values

<function pandas.io.parsers._make_parser_function.<locals>.parser_f(filepath_or_buffer, sep=',', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, doublequote=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)>

In [3]:
iris()


NameError: name 'iris' is not defined

In [ ]:
import scikit as sc
